project:
  output-dir: docs
  type: website
  
execute:
    message: false
    warning: false

  
website:
  title: "Tutorials for DS course materials"
  navbar:
    left:
      - href: index.qmd
        text: Practice
      - href: theory_topics_index.qmd
        text: Theory

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



